#!/usr/bin/env bash

export DOTFILES_PATH="$HOME/.dotfiles"

#mkdir -p $HOME/.config

echo "$DOTFILES_PATH"
echo " 🔄 Applying symlinks"
ln -sf "$DOTFILES_PATH"/git/.gitconfig "$HOME/.gitconfig"
ln -sf "$DOTFILES_PATH"/git/.gitignore_global "$HOME/.gitignore_global"
ln -sf "$DOTFILES_PATH"/shell/zsh/.zshrc "$HOME/.zshrc"
ln -sf "$DOTFILES_PATH"/shell/zsh/.zlogin "$HOME/.zlogin"
ln -sf "$DOTFILES_PATH"/shell/zsh/.zshenv "$HOME/.zshenv"
ln -sf "$DOTFILES_PATH"/shell/zim/.zimrc "$HOME/.zimrc"
echo " 👌 Done!"
