ln -s "$HOME/.dotfiles/git/.gitconfig" "$HOME/.gitconfig"
ln -s "$HOME/.dotfiles/git/.gitignore_global" "$HOME/.gitignore_global"
ln -s "$HOME/.dotfiles/shell/zsh/.zshrc" "$HOME/.zshrc"
ln -s "$HOME/.dotfiles/shell/zsh/.zlogin" "$HOME/.zlogin"
ln -s "$HOME/.dotfiles/shell/zsh/.zshenv" "$HOME/.zshenv"