# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push]

name: Tests

jobs:
#  bash-tests:
#    name: Bash
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os:
#          - macos-10.15
#          - macos-11.0
#          - ubuntu-18.04
#          - ubuntu-20.04
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#      - name: Run tests
#        run: DOT_STUB_DOTRS=true PROJ_HOME=$(pwd)/rust PROJ_NAME=dotrs ./bin/dot self test suite bash
#
#  js-tests:
#    name: Javascript
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os:
#          - macos-10.15
#          - macos-11.0
#          - ubuntu-18.04
#          - ubuntu-20.04
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#      - name: Setup NodeJS
#        uses: actions/setup-node@v1
#      - name: Install tools
#        run: sudo ./bin/dot pkg add jsmin jq
#      - name: Run tests
#        run: ./bin/dot self test suite js

  install-tests:
    name: Install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11.0
          - ubuntu-18.04
          - ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cleanup
        run: cd $HOME && for f in $(ls -a | grep '^\.'); do rm "$f" || true; done
      - name: dot self install
        run: EDITOR=cat TERM=dumb DOT_INSTALL_SKIP_UPDATE=true DOT_DOCOPT=python DOT_FRE=false DOT_FZF=false DOT_NAVI=false DOT_ZIM=false DOT_THEME=simple ./bin/dot self install
      - name: DOTFILES bashrc
        run: cat $HOME/.bashrc | grep DOTFILES
      - name: DOTFILES env variable
        run: bash -c 'source $HOME/.bashrc; env | grep DOTFILES'
      - name: dot version
        run: bash -c 'source $HOME/.bashrc; dot --version | grep -E '^202[0-9]\.[0-9]+\.[0-9]+$''